# Generated by Django 2.2.4 on 2019-12-24 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
