# Generated by Django 2.2.4 on 2019-12-24 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0004_auto_20191225_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewattendance.Branch'),
        ),
    ]
