# Generated by Django 2.2.4 on 2019-12-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0010_auto_20191225_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(help_text='Course ID', max_length=20, unique=True, verbose_name='Course ID')),
                ('course_name', models.CharField(help_text='Name of the teacher', max_length=90, verbose_name='Teacher Name')),
                ('branch_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewattendance.Branch')),
            ],
        ),
    ]
