# Generated by Django 2.2.4 on 2019-12-25 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0012_auto_20191225_1921'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teaching',
            unique_together={('course_id', 'class_id')},
        ),
    ]
