# Generated by Django 3.0.2 on 2020-02-11 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0002_auto_20200211_1540'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttable',
            options={'verbose_name': 'student', 'verbose_name_plural': 'students'},
        ),
    ]
