# Generated by Django 3.0.2 on 2020-02-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studenttable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(help_text='Student ID', max_length=20, unique=True, verbose_name='Student ID')),
                ('name', models.CharField(help_text='Student Name', max_length=20, verbose_name='Student Name')),
                ('status', models.CharField(help_text='Student ID', max_length=10, null=True, verbose_name='Student ID')),
            ],
        ),
    ]
