# Generated by Django 3.0.2 on 2020-02-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploadapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenttable',
            options={'verbose_name': 'student table', 'verbose_name_plural': 'student tables'},
        ),
        migrations.AlterField(
            model_name='studenttable',
            name='status',
            field=models.CharField(default='-', help_text='Status: P/A', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
