# Generated by Django 2.2.4 on 2019-12-25 06:59

from django.db import migrations, models
import viewattendance.models


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0006_auto_20191225_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=viewattendance.models.get_image_path),
        ),
    ]
