# Generated by Django 2.2.4 on 2019-12-25 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0007_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='branch_name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='branch_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewattendance.Branch'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='class_id',
            field=models.CharField(default=1, help_text='Class ID', max_length=20, unique=True, verbose_name='Class ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='viewattendance.Classroom'),
        ),
    ]
