# Generated by Django 2.2.4 on 2019-12-25 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0008_auto_20191225_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_id',
            field=models.CharField(help_text='Class ID', max_length=20, null=True, verbose_name='Class ID'),
        ),
    ]
