# Generated by Django 3.0.3 on 2020-03-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewattendance', '0016_auto_20200303_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(help_text='Course ID', max_length=50, unique=True, verbose_name='Course ID'),
        ),
    ]
